### ISSUE TITLE
login facebook error

### ISSUE THREAD

**Issue by promjai** [robocon/platwo-clinic#1]
facebook_token : CAALxHzIfEEsBAEW97xyJD8Yr2BTpF6IMzndtR3dKFCJZAfPgJZChPPzHkHCa9HJl80wEvU9oJiw5vUE0XgbGzZAaEjC7ksWa9aYlnON4ssFDwjHqIFZCGgQph78PBl0ZCDXbELbkGjLeFMCZCs2wIYLTZCPDxhT9rQxkmUXNyQGHD3wDxRFWw039iKZC1xLZBPk7IEddSirZBC4MSdCk7d7GJ168NeJndfyHVrI91g6Yg4GkfhiWQpFE92

ios_device_token : a3984215b10d7b0b12c4e4b43ac32892fb02ed803146fa847b2d9ad3e842aa25

**Comment by robocon** [comment]
รับทราบครับ เดี๋ยวจะเช็กให้เด้อ ... กำลังหา Aircard อยู่ ขอรายละเอียดเพิ่มเติมหน่อยได้มั้ยครับว่ามันแจ้ง Error ว่าอะไร

**Comment by promjai** [comment]
500 internal server error  อ่ะครับ

![Image of Yaktocat](http://image.ohozaa.com/i/e82/Jj76Ff.png)

**Comment by robocon** [comment]
แก้ไขให้เรียบร้อยแล้วนะครับ
แนะนำวิธีเทสผ่าน Postman สำหรับสมัครสมาชิกด้วย Facebok บน ios ให้ใช้ Parameter แบบนี้ครับ

facebook_token=xxx
ios_device_token[type]=dev หรือ product
ios_device_token[key]=YYY
