### ISSUE TITLE
clear badge

### ISSUE THREAD

**Issue by promjai** [robocon/platwo-clinic#2]
http://clinic-api.pla2app.com/user/notify/clear_badge

มันขึ้น ตัวเลข ตรงแอพ นะครับ แต่มันไม่เคลียให้
คำสั่งเคลีย ต้องเคลีย ผ่าน api อ่ะครับ

**Comment by robocon** [comment]
แก้ไขให้เรียบร้อยแล้วนะครับ

ปล. อย่าลืมส่ง access-token มาใน Header ด้วยนะ
